version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: kbridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
